from google import genai
from dotenv import load_dotenv

def prescribe_remedy(result):

    load_dotenv()
    client = genai.Client()

    prompt = f"""
        You are a skincare expert specializing in natural and homemade remedies.

        The following data represents a skin diagnosis generated by a computer vision model:

        result = {result}

        Instructions:
        1. Analyze the diagnosis carefully.
        2. Suggest remedies that help improve the user's skin condition.
        3. ONLY suggest natural or homemade remedies.
        4. Do NOT recommend chemical compounds or commercial skincare products.
        5. Provide only 5 remedies.

        Return ONLY JSON in this format:

        {{
        "remedy1": "",
        "remedy2": "",
        "remedy3": "",
        "remedy4": "",
        "remedy5": ""
        }}
        """

    response = client.models.generate_content(
        model="gemini-3-flash-preview",
        contents= prompt,
    )
    print("response of LLM - ", response)
    print("Response.text PART- ", response.text)
    return response.text

# sample usage
# result = {
#     "acne" : "severe",
#     "age" : 23,
#     "gender" : "male",
#     "race" : "Indian",
#     "type" : "oily",
#     "other": {"eyebag", "darkspots"}}
# response = prescribe_remedy(result)

# print(response)